on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  accurics-scan:
    runs-on: ubuntu-latest
    name: accurics-scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Accurics Scan
        id: accurics-scan
        uses: docker://accurics/terrascan-action:latest
        with:
          only_warn: true
          verbose: true
          webhook_url: https://4f08-2402-8100-3097-10fd-8db2-fecd-5645-5632.ngrok.io/v1/api/terrascan
          webhook_token: f8ba7d36-e9e1-45a7-9358-aa2955cca7f6
