on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  tenablecs-scan:
    runs-on: ubuntu-latest
    name: tenablecs-scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Tenable.cs Scan
        id: tenablecs-scan
        uses: docker://accurics/terrascan-action:latest
        with:
          only_warn: true
          verbose: true
          webhook_url: https://2c08-103-141-116-116.ngrok.io/v1/api/terrascan
          webhook_token: a7d35e2e-ffaf-438c-b15b-e7bb2bc4d010